import base64
import json
import os
import pickle
import sqlite3

from dotenv import load_dotenv

# Load .env from the backend directory (where this file lives)
load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), '.env'))

from flask import Flask, jsonify, request, send_file
from flask_cors import CORS
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer
from werkzeug.security import check_password_hash, generate_password_hash

# Optional: Firebase Admin for server-side token verification
try:
    import firebase_admin
    from firebase_admin import credentials as fb_creds
    from firebase_admin import auth as fb_auth
    _FB_KEY = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'serviceAccountKey.json')
    if os.path.exists(_FB_KEY) and not firebase_admin._apps:
        firebase_admin.initialize_app(fb_creds.Certificate(_FB_KEY))
        FIREBASE_ADMIN = True
    else:
        FIREBASE_ADMIN = False
except ImportError:
    FIREBASE_ADMIN = False

app = Flask(__name__)
CORS(app, origins="*")

# ── Paths ──────────────────────────────────────────────────────────
BASE_DIR   = os.path.dirname(os.path.abspath(__file__))
HTML_DIR   = os.path.join(BASE_DIR, '..')
TOKEN_PATH = os.path.join(BASE_DIR, 'token.pickle')
CREDS_PATH = os.path.join(BASE_DIR, 'credentials.json')
DB_PATH    = os.path.join(BASE_DIR, 'users.db')

# ── Config ─────────────────────────────────────────────────────────
SCOPES     = ['https://www.googleapis.com/auth/drive.readonly']
SECRET_KEY = os.environ.get('SECRET_KEY', 'dsa-tracker-change-in-production')
serializer = URLSafeTimedSerializer(SECRET_KEY)
_service   = None


# ── Database ───────────────────────────────────────────────────────
def init_db():
    conn = sqlite3.connect(DB_PATH)
    conn.execute('''
        CREATE TABLE IF NOT EXISTS users (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            name          TEXT    NOT NULL,
            email         TEXT    UNIQUE NOT NULL,
            password_hash TEXT    NOT NULL,
            created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    conn.commit()
    conn.close()


def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


init_db()   # runs on startup (works with gunicorn too)


# ── Auth endpoint ─────────────────────────────────────────────────
@app.route('/api/auth/verify')
def verify():
    """Verify a Firebase ID token (or skip if Firebase Admin is not configured)."""
    if not FIREBASE_ADMIN:
        # Firebase Admin not configured — trust frontend auth
        return jsonify({'status': 'ok', 'user': {'name': 'User'}}), 200

    auth_header = request.headers.get('Authorization', '')
    if not auth_header.startswith('Bearer '):
        return jsonify({'error': 'No token provided'}), 401

    id_token = auth_header[7:]
    try:
        decoded = fb_auth.verify_id_token(id_token)
        return jsonify({'user': {
            'id'   : decoded['uid'],
            'name' : decoded.get('name', decoded.get('email', 'User').split('@')[0]),
            'email': decoded.get('email', '')
        }})
    except Exception:
        return jsonify({'error': 'Invalid or expired token'}), 401


# ── Page routes ────────────────────────────────────────────────────
@app.route('/')
def landing():
    return send_file(os.path.join(HTML_DIR, 'index.html'))

@app.route('/auth')
def auth_page():
    return send_file(os.path.join(HTML_DIR, 'auth.html'))

@app.route('/dashboard')
def dashboard():
    return send_file(os.path.join(HTML_DIR, 'dsa_tracker.html'))

@app.route('/firebase-config.js')
def firebase_config_js():
    """Serve Firebase config + app config as JS, injected from env vars."""
    from flask import Response
    cfg = {
        'apiKey':            os.environ.get('FIREBASE_API_KEY', ''),
        'authDomain':        os.environ.get('FIREBASE_AUTH_DOMAIN', ''),
        'projectId':         os.environ.get('FIREBASE_PROJECT_ID', ''),
        'storageBucket':     os.environ.get('FIREBASE_STORAGE_BUCKET', ''),
        'messagingSenderId': os.environ.get('FIREBASE_MESSAGING_SENDER_ID', ''),
        'appId':             os.environ.get('FIREBASE_APP_ID', ''),
        'measurementId':     os.environ.get('FIREBASE_MEASUREMENT_ID', ''),
    }
    root_folder = os.environ.get('ROOT_FOLDER_ID', '')
    js = (
        '// Auto-generated by Flask from environment variables\n'
        f'const firebaseConfig = {json.dumps(cfg, indent=2)};\n'
        f'const APP_CONFIG = {{ rootFolder: "{root_folder}" }};\n'
    )
    return Response(js, mimetype='application/javascript')


# ── Google Drive API ───────────────────────────────────────────────
def get_service():
    global _service
    if _service:
        return _service

    creds = None
    token_env = os.environ.get('GOOGLE_DRIVE_TOKEN')
    if token_env:
        try:
            creds = pickle.loads(base64.b64decode(token_env.encode()))
        except Exception as e:
            print(f"⚠️  Token env var error: {e}")

    if not creds and os.path.exists(TOKEN_PATH):
        with open(TOKEN_PATH, 'rb') as f:
            creds = pickle.load(f)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
            try:
                with open(TOKEN_PATH, 'wb') as f:
                    pickle.dump(creds, f)
            except Exception:
                pass
        else:
            if not os.path.exists(CREDS_PATH):
                raise RuntimeError("No Drive credentials found! See backend/SETUP.md")
            flow  = InstalledAppFlow.from_client_secrets_file(CREDS_PATH, SCOPES)
            creds = flow.run_local_server(port=0)
            with open(TOKEN_PATH, 'wb') as f:
                pickle.dump(creds, f)

    _service = build('drive', 'v3', credentials=creds)
    return _service


@app.route('/api/health')
def health():
    return jsonify({'status': 'ok'})

@app.route('/api/files/<folder_id>')
def list_files(folder_id):
    try:
        svc  = get_service()
        resp = svc.files().list(
            q        = f"'{folder_id}' in parents and trashed=false",
            fields   = "files(id, name, mimeType)",
            orderBy  = "name",
            pageSize = 300
        ).execute()
        return jsonify({'files': resp.get('files', []), 'folderId': folder_id})
    except RuntimeError as e:
        return jsonify({'error': str(e), 'setup_required': True}), 503
    except Exception as e:
        return jsonify({'error': str(e)}), 500


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    print("=" * 54)
    print(f"  DSA Course Tracker  →  http://localhost:{port}")
    print("=" * 54)
    app.run(debug=False, port=port, host='0.0.0.0')
